config/routes.rb
Rails.application.routes.draw do
  root "projects#index"
  resources :projects do
    resources :comments
  end
  resources :project_events, only: :index
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :project
  belongs_to :user
  after_commit { broadcast_append_to "project_#{project_id}"}
  after_save { ProjectEvent.create!(event_type: 2, user: user, project: project, body: body) }
end

app/models/project.rb
class Project < ApplicationRecord
  enum status: {
    'normal': 1,
    'active': 2,
    'completed': 3
  }
  has_many :comments
  has_many :project_events
end

app/models/project_event.rb
class ProjectEvent < ApplicationRecord
  enum event_type: {
    'change status': 1,
    'add comment': 2
  }
  belongs_to :user
  belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :comments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build(comment_params)
    @comment.project_id = params[:project_id]
    @comment.save
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/project_events_controller.rb
class ProjectEventsController < ApplicationController
  # GET /project_events
  def index
    p "111111111111111"
    p params
    @project = Project.find(params[:project_id])
    @project_events = @project.project_events
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :set_statuses_params, only: %i[ create update ]
  before_action :set_project_event, only: :update
  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
    @comments = @project.comments
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    p params
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :status)
    end

  def set_statuses_params
    params[:project][:status] = params[:project][:status].to_i
  end

  def set_project_event
    old_status = @project.status
    @project.status = params[:project][:status]
    if old_status != @project.status
      ProjectEvent.create!(event_type: 1, user: current_user, project: @project,
                           body: "Change status from #{old_status} to #{@project.status}" )
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/comments/_comment.html.slim
= turbo_frame_tag(dom_id(comment))
.row
  = comment.user.email
  =":          "
  = comment.body

app/views/comments/_form.html.slim
.row
  .col-12
    = simple_form_for [@project, Comment.new], data: { \
        action: "turbo:submit-end->comments#resetForm", comments_target: "input_form" } \
        do | f |
      = f.input :body, \
              label: false, \
              input_html: { placeholder: "Type your comment here" }, \
               wrapper_html: { class: "form_control" }, \
                class: "form_control input_group_lg"
      = f.submit "Comment", class: "btn btn-outline-secondary btn-lg"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projects</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/project_events/index.html.slim
p style="color: green" = notice

h1 Project Events for #{@project.name.capitalize}

#project_events
  table
    tr
      th
        | Type
      th
        | Body
    - @project_events.each do |pe|
      tr
        th
          = pe.event_type
        th
          = pe.body

= link_to "Back to project", project_path(@project)

app/views/projects/_form.html.slim
= simple_form_for(@project) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :status, collection: Project.statuses, selected: Project.statuses[@project.status]

  .form-actions
    = f.button :submit

app/views/projects/_project.html.slim
div id="#{dom_id project}" data-controller="comments"
  = turbo_stream_from dom_id(project)
  h1
    = project.name
    br
    = project.status
  #comments[data-comments-target="container"]
    - @comments&.each do |comment|
      = render "comments/comment", comment: comment
  #new_comment
    = render "comments/form", project: project

app/views/projects/edit.html.slim
h1 Editing project

== render "form", project: @project

br

div
  => link_to "Show this project", @project
  '|
  =< link_to "Back to projects", projects_path

app/views/projects/index.html.slim
p style="color: green" = notice

h1 Projects

#projects
  - @projects.each do |project|
    = link_to project.name.capitalize, project
    br

= link_to "New project", new_project_path

app/views/projects/new.html.slim
h1 New project

== render "form", project: @project

br

div
  = link_to "Back to projects", projects_path

app/views/projects/show.html.slim
p style="color: green" = notice

== render @project

div
  => link_to "Edit this project", edit_project_path(@project)
  '|
  =< link_to "Back to projects", projects_path
  '|
  = link_to "Destroy this project", @project, method: :delete
  br
  = link_to "Show this project events", project_events_path(project_id: @project.id)